### ISSUE TITLE
**TypeError:**  Argument #1 ($data) must be of type array, null given,

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_export#5]
**TypeError:** YFormExport\Export::setHeader(): Argument #1 ($data) must be of type array, null given, called in /var/www/vhosts/domain.irgendwas/httpdocs/redaxo/src/addons/yform_export/lib/Export.php on line 194
**File:** redaxo/src/addons/yform_export/lib/Export.php
**Line:** 293

<details>
<summary>Stacktrace</summary>

| Function                           | File                                          | Line     |
| ---------------------------------- | --------------------------------------------- | -------- |
| YFormExport\Export->setHeader      | redaxo/src/addons/yform_export/lib/Export.php | 194      |
| YFormExport\Export->exportTableSet | redaxo/src/addons/yform_export/lib/Export.php | 46       |
| YFormExport\Export->__construct    | redaxo/src/addons/yform_export/boot.php       | 11       |
| require                            | redaxo/src/core/lib/packages/package.php      | 233      |
| rex_package->includeFile           | redaxo/src/core/lib/packages/package.php      | 395      |
| rex_package->boot                  | redaxo/src/core/packages.php                  | 25       |
| {closure}                          | redaxo/src/core/lib/util/timer.php            | 56       |
| rex_timer::measure                 | redaxo/src/core/packages.php                  | 26       |
| {closure}                          | redaxo/src/core/lib/util/timer.php            | 56       |
| rex_timer::measure                 | redaxo/src/core/packages.php                  | 28       |
| include_once                       | redaxo/src/core/backend.php                   | 199      |
| require                            | redaxo/src/core/boot.php                      | 155      |
| require                            | redaxo/index.php                              | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.1.21, MariaDB 10.3.38)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.21     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MariaDB 10.3.38                |
| Character set | utf8mb4                        |
|       Warning | Die verwendete MariaDB-Version 10.3.38 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/16.5.2 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages                 |            |
| -----------------------: | :--------- |
|                  adminer | 1.9.3      |
|                   backup | 2.9.0      |
|                 be_style | 3.2.0      |
|      be_style/customizer | 3.2.0      |
|          be_style/redaxo | 3.2.0      |
|                     cke5 | 4.2.2      |
|                  cropper | 2.0.2      |
|                flatpickr | 1.1.1      |
|               focuspoint | 4.0.4      |
|                 icecoder | 3.0.1      |
|                  install | 2.11.1     |
|              maintenance | 2.9.1      |
|                   mblock | 3.4.12     |
|            media_manager | 2.14.0     |
|         media_negotiator | 2.2.1      |
|                mediapool | 2.13.0     |
|                 metainfo | 2.10.0     |
|                    mform | 6.1.2      |
|               mform/docs | 1.1        |
|         navigation_array | 1.2.1      |
|                phpmailer | 2.12.0     |
|                     plyr | 3.23.0     |
|                  project | dev        |
|         quick_navigation | 6.1.0      |
|       spreadsheet_export | 1.0.0      |
|               statistics | 3.0.1      |
|                structure | 2.15.0     |
|        structure/content | 2.15.0     |
|        structure/history | 2.15.0     |
|         uikit_collection | 3.2.1      |
|                 uploader | 2.4.1      |
|                    users | 2.10.0     |
|                    yform | 4.1.1      |
|              yform/email | 4.1.1      |
|            yform/manager | 4.1.1      |
|             yform_export | 0.0.1      |
|                 yrewrite | 2.10.0     |
| yrewrite_domain_settings | 2.1.2      |
|              zip_install | 1.2        |

</details>

**Comment by eaCe** [comment]
Hm, aber warum ist der Array an der Stelle leer?

**Comment by skerbis** [comment]
Ist ne Einfache Tabelle ohne Relationen oder ähnliches. 
Hier Das Tableset dazu 

```json
{"rex_phone_report":{"table":{"status":1,"table_name":"rex_phone_report","name":"Anruferfassung","description":"","list_amount":50,"list_sortfield":"date","list_sortorder":"DESC","search":1,"hidden":0,"export":1,"import":1,"mass_deletion":0,"mass_edit":0,"schema_overwrite":1,"history":1},"fields":[{"table_name":"rex_phone_report","prio":1,"type_id":"value","type_name":"date","db_type":"date","list_hidden":0,"search":1,"name":"date","label":"Datum","not_required":"","attributes":"{\"class\": \"flatpickr\", \"data-altFormat\": \"j. F, Y\"}","no_db":"0","year_start":"2023","year_end":"2024","format":"d.m.Y","current_date":"1","widget":"input:text","notice":""},{"table_name":"rex_phone_report","prio":2,"type_id":"value","type_name":"choice","db_type":"text","list_hidden":0,"search":1,"name":"grund","label":"Grund des Anrufs","not_required":"","multiple":"1","expanded":"0","choices":"Probleme mit der Miete=Miete,Energiesperre droht=Energie,Preisanstieg=Inflation,Kinderarmut droht=Kinderarmut","choice_attributes":"","placeholder":"Bitte ausw\u00e4hlen","attributes":"{\"class\": \"form-control selectpicker\",\"data-live-search\": \"true\"}","no_db":"0","group_attributes":"","notice":"Es k\u00f6nnen mehrere Gr\u00fcnde ausgew\u00e4hlt werden.","default":""},{"table_name":"rex_phone_report","prio":3,"type_id":"value","type_name":"textarea","db_type":"text","list_hidden":0,"search":0,"name":"sonstige","label":"Sonstige Gr\u00fcnde","not_required":"","attributes":"","no_db":"0","notice":"Bei sonstigen Anrufgr\u00fcnden bitte beschreiben","default":""},{"table_name":"rex_phone_report","prio":4,"type_id":"value","type_name":"checkbox","db_type":"tinyint(1)","list_hidden":0,"search":1,"name":"vermittlung","label":"Vermittlung erfolgt","not_required":"","attributes":"","no_db":"0","notice":"","default":"0","output_values":"\u25a2,\u25a3"},{"table_name":"rex_phone_report","prio":5,"type_id":"value","type_name":"choice","db_type":"text","list_hidden":0,"search":0,"name":"kampagne","label":"Wodurch auf die Kampagne aufmerksam geworden","not_required":"","multiple":"1","expanded":"0","choices":"Flyer\/Plakate\/Banner=flyer,Infostand=infostand,Internet=web,Presse\/Anzeigen=pr","choice_attributes":"","placeholder":"","attributes":"{\"class\": \"form-control selectpicker\",\"data-live-search\": \"true\"}","no_db":"0","group_attributes":"","notice":"Es k\u00f6nnen mehrere Medien ausgew\u00e4hlt werden.","default":""},{"table_name":"rex_phone_report","prio":6,"type_id":"value","type_name":"textarea","db_type":"text","list_hidden":0,"search":0,"name":"andere","label":"Sonstiges","not_required":"","attributes":"","no_db":"0","notice":"Bei Bedarf ausf\u00fcllen","default":""},{"table_name":"rex_phone_report","prio":7,"type_id":"value","type_name":"number","db_type":"","list_hidden":0,"search":0,"name":"alter","label":"Alter","not_required":"","attributes":"","no_db":"0","widget":"input:text","notice":"Alter des Anrufenden","default":"","precision":"2","scale":"0","unit":"Jahre"},{"table_name":"rex_phone_report","prio":8,"type_id":"value","type_name":"be_user","db_type":"varchar(191)","list_hidden":1,"search":0,"name":"user","label":"Nutzer erstellt","not_required":"","only_empty":"1","show_value":"0"},{"table_name":"rex_phone_report","prio":9,"type_id":"value","type_name":"be_user","db_type":"varchar(191)","list_hidden":1,"search":0,"name":"user_edit","label":" Bearbeitet","not_required":"","only_empty":"0","show_value":"0"}]}}

```

**Comment by eaCe** [comment]
Danke, schau ich mir die Tage an

**Comment by eaCe** [comment]
@skerbis kann es sein das du versuchst eine leere Tabelle zu exportieren? Dann sollte natürlich auch der Whoops abgefangen werden, aber zumindest kann ich es so reproduzieren

**Comment by skerbis** [comment]
Nein. Die Tabelle ist nicht leer.

**Comment by eaCe** [comment]
OK das ist komisch.

**Comment by eaCe** [comment]
@skerbis ich habe nun eine Prüfung eingebaut, wenn die Daten leer sind. Sobald aber ein Eintrag vorhanden ist, habe ich damit keine Probleme mehr

**Comment by eaCe** [comment]
@skerbis hat sich das mit deinem PR erledigt?

**Comment by eaCe** [comment]
Ping @skerbis

**Comment by skerbis** [comment]
ich sag mal js
